/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jv_example_RockingJNI_FileDumper */

#ifndef _Included_com_jv_example_RockingJNI_FileDumper
#define _Included_com_jv_example_RockingJNI_FileDumper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jv_example_RockingJNI_FileDumper
 * Method:    dumpFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jv_example_RockingJNI_FileDumper_dumpFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
